# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimar√£es (Forschungszentrum Juelich GmbH) 

############
# Graph Page
############
- graphpage:
    name:          "steptimelines"
    filepath:      "$outputdir/ll/graphpage_steptimelines.json"
    columns: 1
    graphs: 
       - name: "DBupdate"
         xcol: "dt_ms"
         height: "400px"
         layout:
           showlegend: false
           xaxis: 
               type: "date"
          #  yaxis: 
          #      title: "Substep Nr"
          #  legend:
          #      x: "0.0"
          #      xref: "x domain"
          #      xanchor: "left"
          #      y: "1"
          #      yanchor: "top"
           title:
               text: "<b>DBupdate substep timeline<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           - name:   "DBupdate"
             ycol: "id"
             basecol: "ts_ms"
             colorby: "groupnr"
             onhover:
              #  - ts_ms: { name: 'Start time', format: '|%Y/%m/%d %H:%M:%S.%L'}
               id: { name: 'Step name'}
               dt_ms: { name: 'Duration', format: ':.2f', factor: 0.001, units: 's'}
               cmplx: { name: 'Complexity' }
             color:
               - '#FF0000'
               - '#00FF00'
               - '#0000FF'
               - '#00FFFF'
               - '#FF00FF'
               - '#FFFF00'
            #  ycol: "nr"
            #  yaxis:  "y"
             type:   "bar"
             orientation: 'h'
             datapath: "data/_internal/steptimings/steptimeline_DBupdate.csv"  
       - name: "jobreport"
         xcol: "dt_ms"
         height: "600px"
         layout:
           showlegend: false
           xaxis: 
               type: "date"
          #  yaxis: 
          #      title: "Substep Nr"
          #  legend:
          #      x: "0.0"
          #      xref: "x domain"
          #      xanchor: "left"
          #      y: "1"
          #      yanchor: "top"
           title:
               text: "<b>Jobreport substep timeline<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           - name:   "Jobreport"
             ycol: "id"
             basecol: "ts_ms"
             colorby: "groupnr"
             onhover:
              #  - ts_ms: { name: 'Start time', format: '|%Y/%m/%d %H:%M:%S.%L'}
               id: { name: 'Step name'}
               dt_ms: { name: 'Duration', format: ':.2f', factor: 0.001, units: 's'}
               cmplx: { name: 'Complexity' }
             color:
               - '#FF0000'
               - '#00FF00'
               - '#0000FF'
               - '#00FFFF'
               - '#FF00FF'
               - '#FFFF00'
            #  ycol: "nr"
            #  yaxis:  "y"
             type:   "bar"
             orientation: 'h'
             datapath: "data/_internal/steptimings/steptimeline_jobreport.csv"
       - name: "Part2"
         xcol: "dt_ms"
         height: "300px"
         layout:
           showlegend: false
           xaxis: 
               type: "date"
          #  yaxis: 
          #      title: "Substep Nr"
          #  legend:
          #      x: "0.0"
          #      xref: "x domain"
          #      xanchor: "left"
          #      y: "1"
          #      yanchor: "top"
           title:
               text: "<b>Part2 timeline<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           - name:   "Part2"
             ycol: "id"
             basecol: "ts_ms"
             colorby: "groupnr"
             onhover:
              #  - ts_ms: { name: 'Start time', format: '|%Y/%m/%d %H:%M:%S.%L'}
               id: { name: 'Step name'}
               dt_ms: { name: 'Duration', format: ':.2f', factor: 0.001, units: 's'}
               cmplx: { name: 'Complexity' }
             color:
               - '#FF0000'
               - '#00FF00'
               - '#0000FF'
               - '#00FFFF'
               - '#FF00FF'
               - '#FFFF00'
            #  ycol: "nr"
            #  yaxis:  "y"
             type:   "bar"
             orientation: 'h'
             datapath: "data/_internal/steptimings/steptimeline_PART2.csv"
       - name: "Part3"
         xcol: "dt_ms"
         height: "300px"
         layout:
           showlegend: false
           xaxis: 
               type: "date"
          #  yaxis: 
          #      title: "Substep Nr"
          #  legend:
          #      x: "0.0"
          #      xref: "x domain"
          #      xanchor: "left"
          #      y: "1"
          #      yanchor: "top"
           title:
               text: "<b>Part3 timeline<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           - name:   "Part3"
             ycol: "id"
             basecol: "ts_ms"
             colorby: "groupnr"
             onhover:
              #  - ts_ms: { name: 'Start time', format: '|%Y/%m/%d %H:%M:%S.%L'}
               id: { name: 'Step name'}
               dt_ms: { name: 'Duration', format: ':.2f', factor: 0.001, units: 's'}
               cmplx: { name: 'Complexity' }
             color:
               - '#FF0000'
               - '#00FF00'
               - '#0000FF'
               - '#00FFFF'
               - '#FF00FF'
               - '#FFFF00'
            #  ycol: "nr"
            #  yaxis:  "y"
             type:   "bar"
             orientation: 'h'
             datapath: "data/_internal/steptimings/steptimeline_PART3.csv"
       - name: "Part4"
         xcol: "dt_ms"
         height: "300px"
         layout:
           showlegend: false
           xaxis: 
               type: "date"
          #  yaxis: 
          #      title: "Substep Nr"
          #  legend:
          #      x: "0.0"
          #      xref: "x domain"
          #      xanchor: "left"
          #      y: "1"
          #      yanchor: "top"
           title:
               text: "<b>Part4 timeline<b>"
               font: 
                  family: 'Arial'
                  size: 16
               xref: "x domain"
               x:    "0.5"
               xanchor: "center"
         traces:
           - name:   "Part4"
             ycol: "id"
             basecol: "ts_ms"
             colorby: "groupnr"
             onhover:
              #  - ts_ms: { name: 'Start time', format: '|%Y/%m/%d %H:%M:%S.%L'}
               id: { name: 'Step name'}
               dt_ms: { name: 'Duration', format: ':.2f', factor: 0.001, units: 's'}
               cmplx: { name: 'Complexity' }
             color:
               - '#FF0000'
               - '#00FF00'
               - '#0000FF'
               - '#00FFFF'
               - '#FF00FF'
               - '#FFFF00'
            #  ycol: "nr"
            #  yaxis:  "y"
             type:   "bar"
             orientation: 'h'
             datapath: "data/_internal/steptimings/steptimeline_PART4.csv"
