# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Filipe Guimar√£es (Forschungszentrum Juelich GmbH) 

SYSTEM: 
  dc-cpu: 
    cores: 128
    mem: 512
  dc-cpu-large: 
    cores: 128
    mem: 512
  dc-gpu: 
    cores: 128
    mem: 512
    memgpu: 40
  dc-ipu: 
    cores: 96
    mem: 512
  dc-mi200:
    cores: 48
    mem: 512
    memgpu: 64
  dc-arm:
    cores: 80
    mem: 512
    memgpu: 40
  dc-gpu-large: 
    cores: 128
    mem: 512
    memgpu: 40
  dc-cpu-bigmem: 
    cores: 128
    mem: 1024
  dc-cpu-devel: 
    cores: 128
    mem: 512
  dc-cpu-devel-sw: 
    cores: 128
    mem: 512
  dc-gpu-devel: 
    cores: 128
    mem: 512
    memgpu: 40
  dc-gpu-devel-sw: 
    cores: 128
    mem: 512
    memgpu: 40
  dc-spr:
    cores: 112
    mem: 1024
  dc-h100: 
    cores: 72
    mem: 512
    memgpu: 80
  dc-gh:
    cores: 72
    mem: 480
    memgpu: 96
  dc-wai:
    cores: 64
    mem: 512
    memgpu: 96
  booster:
    cores: 48
    mem: 512
    memgpu: 40
  develbooster: 
    cores: 48
    mem: 512
    memgpu: 40
  dc-maint: 
    cores: 128
    mem: 512
    memgpu: 40
  maint: 
    cores: 128
    mem: 512
    memgpu: 40
