# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 
#    Filipe Guimar√£es (Forschungszentrum Juelich GmbH) 

# show pattern for GPU footer graph, show the graphs only if queue eq ...
#show_pattern: 
#  Queue: "gpu"
    # xx: 
    #    - val1
    #    - val2         
    # owner: "neubacher1"
