# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

x:
  header: 'ts'
  type: 'int32'
y:
  header: 'nodeid'
  type: 'str'
  name: 'Node'
# Cores:
#   _file_header: 'coreusagenodefile'
#   _datapoints_header: 'cores_ndps'
#   Physical Cores Usage:
#     x: 
#       header: 'coreid'
#       type: 'int16'
#       name: 'Core ID'
#     header: 'usage1_avg'
#     type: 'float16'
#     unit: '%'
#     log: False
#     note: ''
#     cmap: 'cmc.hawaii'
#     lim: [0,100]
#     description: 'Average physical core usage along the runtime of the job (max. 100%)'
#   Logical Cores Usage:
#     x: 
#       header: 'coreid'
#       type: 'int16'
#       name: 'Core ID'
#     header: 'usage2_avg'
#     type: 'float16'
#     unit: '%'
#     log: False
#     note: ''
#     cmap: 'cmc.hawaii'
#     lim: [0,100]
#     description: 'Average logical core usage along the runtime of the job (max. 100%)'

CPU:
  _file_header: 'loadmemnodefile'
  _datapoints_header: 'ld_ndps'
  _max_graph_per_page: 3
  # Usage:
  #   header: 'usage'
  #   type: 'float16'
  #   unit: '%'
  #   log: False
  #   note: ''
  #   cmap: 'cmc.hawaii'
  #   lim: [0,100]
  #   description: 'Average core usage among all cores in the nodes (max. 200%)'
  # Number of Physical Cores Used:
  #   header: 'used_cores_phys'
  #   type: 'int16'
  #   unit: 'cores'
  #   log: False
  #   note: ''
  #   cmap: 'cmc.hawaii'
  #   lim: [0,'cores']
  #   description: 'Number of physical cores with usage >25%'
  # Number of Logical Cores Used:
  #   header: 'used_cores_logic'
  #   type: 'int16'
  #   unit: 'cores'
  #   log: False
  #   note: ''
  #   cmap: 'cmc.hawaii'
  #   lim: [0,'cores']
  #   description: 'Number of logical cores with usage >25%'
  Load:
    header: 'load'
    type: 'float16'
    unit: ''
    log: False
    note: ''
    cmap: 'cmc.hawaii'
    lim: [0,'cores']
    description: '1-min CPU load average'
  Memory Usage:
    header: 'used_mem'
    type: 'float32'
    unit: 'GiB'
    log: False
    note: ''
    cmap: 'cmc.hawaii'
    lim: [0,'mem']
    description: 'Amount of allocated RAM memory (in GiB) in the node'
GPU:
  _file_header: 'gpunodefile'
  _datapoints_header: 'gpu_ndps'
  y:
    name: 'GPU'
  Usage: 
    header: 'gpu_usage'
    type: 'float16'
    unit: '%'
    log: False
    note: ''
    cmap: 'cmc.hawaii'
    lim: [0,100]
    description: 'Percent of time over the past sample period during which one or more kernels was executing on the GPU'
  Memory Usage: 
    header: 'gpu_memu'
    type: 'float32'
    unit: 'GiB'
    log: False
    note: ''
    cmap: 'cmc.hawaii'
    lim: [0,'memgpu']
    description: 'Amount of memory (in GiB) used on the device by the context'
  Power: 
    header: 'gpu_pu'
    type: 'float32'
    unit: 'W'
    log: False
    note: ''
    cmap: 'cmc.hawaii'
    lim:  False
    description: 'Power usage for (in Watts) for the GPU and its associated circuitry (e.g. memory)'
  Temperature: 
    header: 'gpu_temp'
    type: 'float32'
    unit: '°C'
    log: False
    note: ''
    cmap: 'cmc.lajolla_r'
    lim: [40,83]
    description: 'Current Temperature (in Celsius) on the GPU'
  Clk Throttle Reason:
    header: 'gpu_clkr'  
    type: 'int16'  
    unit: '#'  
    log: 2  
    note: "1:GpuIdle / 2:AppClkSet\n4:SwPwrCap / 8:HWSlowDown\n16:SyncBoost\n32:SwThermSlDwn\n64:HwThermSlDwn\n128:PwrBrakeSlDwn"  
    cmap: 'cmc.hawaii'
    lim: False  
    skip_when_all: NaN
    description: 'Information about factors that are reducing the frequency of clocks'
  StreamMP Clk:
    header: 'gpu_sclk'  
    type: 'float32'  
    unit: 'MHz'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Current frequency in MHz of SM (Streaming Multiprocessor) clock'
  Memory Usage Rate:
    header: 'gpu_memur'  
    type: 'float32'  
    unit: '%'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: [0,100]  
    description: 'Percent of time over the past sample period during which global (device) memory was being read or written'
  Memory Clk:
    header: 'gpu_clk'  
    type: 'float32'  
    unit: 'MHz'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Current frequency of the memory clock, in MHz'
  Performance State:
    header: 'gpu_pfst'  
    type: 'int16'  
    unit: '#'  
    log: False  
    note: "0: Highest performance\n\n12: Lowest performance"
    cmap: 'cmc.hawaii'
    lim: [0,15] 
    skip_when_all: 0
    description: 'The current performance state for the GPU. States range from P0 (maximum performance) to P12 (minimum performance)'
  PCIE TX:
    header: 'gpu_pcie_tx'  
    type: 'float32'  
    unit: 'GiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False
    description: 'The GPU-centric transmission throughput across the PCIe bus (in GiB/s) over the past 20ms'
  PCIE RX:
    header: 'gpu_pcie_rx'  
    type: 'float32'  
    unit: 'GiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False
    description: 'The GPU-centric receive throughput across the PCIe bus (in GiB/s) over the past 20ms'

File System \$HOME:
  _file_header: 'fshomenodefile'  
  _datapoints_header: 'fs_home_ndps'  
  _fill_with: 0.0
  Read: 
    header: 'MbrR'  
    type: 'float32'  
    unit: 'MiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False
    description: 'Average read data rate (in MiB/s) in the last minute'
  Write:
    header: 'MbwR'  
    type: 'float32'  
    unit: 'MiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Average write data rate (in MiB/s) in the last minute'
  Open/Close Operations:
    header: 'ocR'  
    type: 'float32'  
    unit: 'op./s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False
    description: 'Average operation rate (in operations/s) in the last minute'

File System \$PROJECT:
  _file_header: 'fsprojectnodefile'  
  _datapoints_header: 'fs_project_ndps'  
  _fill_with: 0.0
  Read: 
    header: 'MbrR'  
    type: 'float32'  
    unit: 'MiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Average read data rate (in MiB/s) in the last minute'
  Write:
    header: 'MbwR'  
    type: 'float32'  
    unit: 'MiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Average write data rate (in MiB/s) in the last minute'
  Open/Close Operations:
    header: 'ocR'  
    type: 'float32'  
    unit: 'op./s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False
    description: 'Average operation rate (in operations/s) in the last minute'

File System \$SCRATCH:
  _file_header: 'fsscratchnodefile'  
  _datapoints_header: 'fs_scratch_ndps'  
  _fill_with: 0.0
  Read: 
    header: 'MbrR'  
    type: 'float32'  
    unit: 'MiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Average read data rate (in MiB/s) in the last minute'
  Write:
    header: 'MbwR'  
    type: 'float32'  
    unit: 'MiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Average write data rate (in MiB/s) in the last minute'
  Open/Close Operations:
    header: 'ocR'  
    type: 'float32'  
    unit: 'op./s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False
    description: 'Average operation rate (in operations/s) in the last minute'

File System \$FASTDATA:
  _file_header: 'fsfastdatanodefile'  
  _datapoints_header: 'fs_fastdata_ndps'  
  _fill_with: 0.0
  Read: 
    header: 'MbrR'  
    type: 'float32'  
    unit: 'MiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Average read data rate (in MiB/s) in the last minute'
  Write:
    header: 'MbwR'  
    type: 'float32'  
    unit: 'MiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Average write data rate (in MiB/s) in the last minute'
  Open/Close Operations:
    header: 'ocR'  
    type: 'float32'  
    unit: 'op./s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False
    description: 'Average operation rate (in operations/s) in the last minute'

Interconnect:
  _file_header: 'fabricnodefile'  
  _datapoints_header: 'fa_ndps'  
  _fill_with: 0.0
  Data Input: 
    header: 'mbin'  
    type: 'float32'  
    unit: 'MiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Average data input throughput (in MiB/s) in the last minute'
  Data Output: 
    header: 'mbout'  
    type: 'float32'  
    unit: 'MiB/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Average data output throughput (in MiB/s) in the last minute'
  Packet Input:
    header: 'pckin'  
    type: 'float32'  
    unit: 'pkt/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False  
    description: 'Average package input throughput (in pkt/s) in the last minute'
  Packet Output:
    header: 'pckout'  
    type: 'float32'  
    unit: 'pkt/s'  
    log: False  
    note: ''  
    cmap: 'cmc.hawaii'
    lim: False
    description: 'Average package output throughput (in pkt/s) in the last minute'

User:
  _file_header: 'jmcfile'  
  _datapoints_header: 'jmc_ndps' 
  _section: 'jmc'  
  