# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

# all file systems
######################

- dataset:
    name: fsusage_node_all_dat
    set:        fsusage_all
    FORALL:     'P,U,J:VAR_project_user_job'
    filepath:   '$outputdir/projects/$P/$U/FSusage_${J}_all_node.dat'
    columns:        'jobid,ts,nodeid,MbwR,MbrR,ocR'
    column_convert: ''
    column_filemap: 'J:jobid'
    column_ts:      'ts'
    sql_where:      '(D.MbwR+D.MbrR+D.ocR)>0.0'
    format:         'dat'
    format_str:      '%-10s %10d %12s %8.6f %8.6f %e'
    format_header:   '%-10s %10s %12s %8s %8s %8s'
    column_filemap: 'J:jobid'
    data_database:   fsusagestate_all
    data_table:      fsusage_by_jobid_nodeid_ts
    stat_database:   jobreport_stat_fsusage_all
    stat_table:      datasetstat_node_dat
    mngt_actions:   'compress_finished_files,archive_jobs_files'

- dataset:
    name: fsusage_all_csv
    set:        fsusage_all
    FORALL:     'P,U,J:VAR_project_user_job'
    filepath:   '$outputdir/projects/$P/$U/FSusage_${J}_all.csv'
    columns:        'ts,MbwR_min,MbwR_avg,MbwR_max,MbrR_min,MbrR_avg,MbrR_max,ocR_min,ocR_avg,ocR_max'
    header:         'date,MBwrite_sec,MBread_sec,MOpenClose_sec'
    column_convert: 'ts->todate_1'
    format_str:      '%s,%f;%f;%f,%f;%f;%f,%f;%f;%f'
    column_filemap: 'J:jobid'
    column_ts:      'ts'
    format:         'csv'
    column_filemap: 'J:jobid'
    data_database:   fsusagestate_all
    data_table:      fsusage_aggr_by_jobid_ts
    stat_database:   jobreport_stat_fsusage_all
    stat_table:      datasetstat_csv
    mngt_actions:   'compress_finished_files,archive_jobs_files'
    
# project file systems
######################

- dataset:
    name: fsusage_node_project_dat
    set:        fsusage_project
    FORALL:     'P,U,J:VAR_project_user_job'
    filepath:   '$outputdir/projects/$P/$U/FSusage_${J}_project_node.dat'
    columns:        'jobid,ts,nodeid,MbwR,MbrR,ocR'
    column_convert: ''
    column_filemap: 'J:jobid'
    column_ts:      'ts'
    sql_where:      '(D.MbwR+D.MbrR+D.ocR)>0.0'
    format:         'dat'
    format_str:      '%-10s %10d %12s %8.6f %8.6f %8.6f'
    format_header:   '%-10s %10s %12s %8s %8s %8s'
    column_filemap: 'J:jobid'
    data_database:   fsusagestate_project
    data_table:      fsusage_by_jobid_nodeid_ts
    stat_database:   jobreport_stat_fsusage_project
    stat_table:      datasetstat_node_dat
    mngt_actions:   'compress_finished_files,archive_jobs_files'

- dataset:
    name: fsusage_project_csv
    set:        fsusage_project
    FORALL:     'P,U,J:VAR_project_user_job'
    filepath:   '$outputdir/projects/$P/$U/FSusage_${J}_project.csv'
    columns:        'ts,MbwR_min,MbwR_avg,MbwR_max,MbrR_min,MbrR_avg,MbrR_max,ocR_min,ocR_avg,ocR_max'
    header:         'date,MBwrite_sec,MBread_sec,MOpenClose_sec'
    column_convert: 'ts->todate_1'
    format_str:      '%s,%f;%f;%f,%f;%f;%f,%f;%f;%f'
    column_filemap: 'J:jobid'
    column_ts:      'ts'
    format:         'csv'
    column_filemap: 'J:jobid'
    data_database:   fsusagestate_project
    data_table:      fsusage_aggr_by_jobid_ts
    stat_database:   jobreport_stat_fsusage_project
    stat_table:      datasetstat_csv
    mngt_actions:   'compress_finished_files,archive_jobs_files'
    
# scratch file systems
######################

- dataset:
    name: fsusage_node_scratch_dat
    set:        fsusage_scratch
    FORALL:     'P,U,J:VAR_project_user_job'
    filepath:   '$outputdir/projects/$P/$U/FSusage_${J}_scratch_node.dat'
    columns:        'jobid,ts,nodeid,MbwR,MbrR,ocR'
    column_convert: ''
    column_filemap: 'J:jobid'
    column_ts:      'ts'
    sql_where:      '(D.MbwR+D.MbrR+D.ocR)>0.0'
    format:         'dat'
    format_str:      '%-10s %10d %12s %8.6f %8.6f %8.6f'
    format_header:   '%-10s %10s %12s %8s %8s %8s'
    column_filemap: 'J:jobid'
    data_database:   fsusagestate_scratch
    data_table:      fsusage_by_jobid_nodeid_ts
    stat_database:   jobreport_stat_fsusage_scratch
    stat_table:      datasetstat_node_dat
    mngt_actions:   'compress_finished_files,archive_jobs_files'
    
- dataset:
    name: fsusage_scratch_csv
    set:        fsusage_scratch
    FORALL:     'P,U,J:VAR_project_user_job'
    filepath:   '$outputdir/projects/$P/$U/FSusage_${J}_scratch.csv'
    columns:        'ts,MbwR_min,MbwR_avg,MbwR_max,MbrR_min,MbrR_avg,MbrR_max,ocR_min,ocR_avg,ocR_max'
    header:         'date,MBwrite_sec,MBread_sec,MOpenClose_sec'
    column_convert: 'ts->todate_1'
    format_str:      '%s,%f;%f;%f,%f;%f;%f,%f;%f;%f'
    column_filemap: 'J:jobid'
    column_ts:      'ts'
    format:         'csv'
    column_filemap: 'J:jobid'
    data_database:   fsusagestate_scratch
    data_table:      fsusage_aggr_by_jobid_ts
    stat_database:   jobreport_stat_fsusage_scratch
    stat_table:      datasetstat_csv
    mngt_actions:   'compress_finished_files,archive_jobs_files'

# fastdata file systems
#######################

- dataset:
    name: fsusage_node_fastdata_dat
    set:        fsusage_fastdata
    FORALL:     'P,U,J:VAR_project_user_job'
    filepath:   '$outputdir/projects/$P/$U/FSusage_${J}_fastdata_node.dat'
    columns:        'jobid,ts,nodeid,MbwR,MbrR,ocR'
    column_convert: ''
    column_filemap: 'J:jobid'
    column_ts:      'ts'
    sql_where:      '(D.MbwR+D.MbrR+D.ocR)>0.0'
    format:         'dat'
    format_str:      '%-10s %10d %12s %8.6f %8.6f %f'
    format_header:   '%-10s %10s %12s %8s %8s %8s'
    column_filemap: 'J:jobid'
    data_database:   fsusagestate_fastdata
    data_table:      fsusage_by_jobid_nodeid_ts
    stat_database:   jobreport_stat_fsusage_fastdata
    stat_table:      datasetstat_node_dat
    mngt_actions:   'compress_finished_files,archive_jobs_files'

- dataset:
    name: fsusage_fastdata_csv
    set:        fsusage_fastdata
    FORALL:     'P,U,J:VAR_project_user_job'
    filepath:   '$outputdir/projects/$P/$U/FSusage_${J}_fastdata.csv'
    columns:        'ts,MbwR_min,MbwR_avg,MbwR_max,MbrR_min,MbrR_avg,MbrR_max,ocR_min,ocR_avg,ocR_max'
    header:         'date,MBwrite_sec,MBread_sec,MOpenClose_sec'
    column_convert: 'ts->todate_1'
    format_str:      '%s,%f;%f;%f,%f;%f;%f,%f;%f;%f'
    column_filemap: 'J:jobid'
    column_ts:      'ts'
    format:         'csv'
    column_filemap: 'J:jobid'
    data_database:   fsusagestate_fastdata
    data_table:      fsusage_aggr_by_jobid_ts
    stat_database:   jobreport_stat_fsusage_fastdata
    stat_table:      datasetstat_csv
    mngt_actions:   'compress_finished_files,archive_jobs_files'

 # home file systems
#######################

- dataset:
    name: fsusage_node_home_dat
    set:        fsusage_home
    FORALL:     'P,U,J:VAR_project_user_job'
    filepath:   '$outputdir/projects/$P/$U/FSusage_${J}_home_node.dat'
    columns:        'jobid,ts,nodeid,MbwR,MbrR,ocR'
    column_convert: ''
    column_filemap: 'J:jobid'
    column_ts:      'ts'
    sql_where:      '(D.MbwR+D.MbrR)>0.000001 OR (D.ocR>0.001)'
    format:         'dat'
    format_str:      '%-10s %10d %12s %8.6f %8.6f %8.6f'
    format_header:   '%-10s %10s %12s %8s %8s %8s'
    column_filemap: 'J:jobid'
    data_database:   fsusagestate_home
    data_table:      fsusage_by_jobid_nodeid_ts
    stat_database:   jobreport_stat_fsusage_home
    stat_table:      datasetstat_node_dat
    mngt_actions:   'compress_finished_files,archive_jobs_files'

- dataset:
    name: fsusage_home_csv
    set:        fsusage_home
    FORALL:     'P,U,J:VAR_project_user_job'
    filepath:   '$outputdir/projects/$P/$U/FSusage_${J}_home.csv'
    columns:        'ts,MbwR_min,MbwR_avg,MbwR_max,MbrR_min,MbrR_avg,MbrR_max,ocR_min,ocR_avg,ocR_max'
    header:         'date,MBwrite_sec,MBread_sec,MOpenClose_sec'
    column_convert: 'ts->todate_1'
    format_str:      '%s,%f;%f;%f,%f;%f;%f,%f;%f;%f'
    column_filemap: 'J:jobid'
    column_ts:      'ts'
    format:         'csv'
    column_filemap: 'J:jobid'
    data_database:   fsusagestate_home
    data_table:      fsusage_aggr_by_jobid_ts
    stat_database:   jobreport_stat_fsusage_home
    stat_table:      datasetstat_csv
    mngt_actions:   'compress_finished_files,archive_jobs_files'


# System I/O Overview
#######################

- dataset:
    name: sysstat_io_scratch_csv
    set:        fsusage
    filepath:   '$outputdir/_sysstat/sysstat_IO_SCRATCH_span.csv'
    columns:        'ts,MbrR_sum,MbwR_sum,ocR_sum'
    header:         'date,MbrR_sum,MbwR_sum,ocR_sum'
    format_str:      '%s,%f,%f,%f'
    column_convert: 'ts->todate_1'
    format:         'csv'
    column_ts:      'ts'
    time_aggr:      'span'
    renew:          'daily(14:00)'
    data_database:   fsusagestate_scratch
    data_table:      fsusage_time_aggr_ts
    stat_database:   jobreport_stat_fsusage_scratch
    stat_table:      datasetstat

- dataset:
    name: sysstat_io_project_csv
    set:        fsusage
    filepath:   '$outputdir/_sysstat/sysstat_IO_PROJECT_span.csv'
    columns:        'ts,MbrR_sum,MbwR_sum,ocR_sum'
    header:         'date,MbrR_sum,MbwR_sum,ocR_sum'
    format_str:      '%s,%f,%f,%f'
    column_convert: 'ts->todate_1'
    format:         'csv'
    column_ts:      'ts'
    time_aggr:      'span'
    renew:          'daily(14:00)'
    data_database:   fsusagestate_project
    data_table:      fsusage_time_aggr_ts
    stat_database:   jobreport_stat_fsusage_project
    stat_table:      datasetstat

- dataset:
    name: sysstat_io_fastdata_csv
    set:        fsusage
    filepath:   '$outputdir/_sysstat/sysstat_IO_FASTDATA_span.csv'
    columns:        'ts,MbrR_sum,MbwR_sum,ocR_sum'
    header:         'date,MbrR_sum,MbwR_sum,ocR_sum'
    format_str:      '%s,%f,%f,%f'
    column_convert: 'ts->todate_1'
    format:         'csv'
    column_ts:      'ts'
    time_aggr:      'span'
    renew:          'daily(14:00)'
    data_database:   fsusagestate_fastdata
    data_table:      fsusage_time_aggr_ts
    stat_database:   jobreport_stat_fsusage_fastdata
    stat_table:      datasetstat

- dataset:
    name: sysstat_io_home_csv
    set:        fsusage
    filepath:   '$outputdir/_sysstat/sysstat_IO_HOME_span.csv'
    columns:        'ts,MbrR_sum,MbwR_sum,ocR_sum'
    header:         'date,MbrR_sum,MbwR_sum,ocR_sum'
    format_str:      '%s,%f,%f,%f'
    column_convert: 'ts->todate_1'
    format:         'csv'
    column_ts:      'ts'
    time_aggr:      'span'
    renew:          'daily(14:00)'
    data_database:   fsusagestate_home
    data_table:      fsusage_time_aggr_ts
    stat_database:   jobreport_stat_fsusage_home
    stat_table:      datasetstat

- dataset:
    name: sysstat_io_all_csv
    set:        fsusage
    filepath:   '$outputdir/_sysstat/sysstat_IO_ALL_span.csv'
    columns:        'ts,MbrR_sum,MbwR_sum,ocR_sum'
    header:         'date,MbrR_sum,MbwR_sum,ocR_sum'
    format_str:      '%s,%f,%f,%f'
    column_convert: 'ts->todate_1'
    format:         'csv'
    column_ts:      'ts'
    time_aggr:      'span'
    renew:          'daily(14:00)'
    data_database:   fsusagestate_all
    data_table:      fsusage_time_aggr_ts
    stat_database:   jobreport_stat_fsusage_all
    stat_table:      datasetstat
