- dataset:
    name: jumonc_dat
    set:        jumonc
    FORALL:     'P,U,J:VAR_project_user_job_jumonc'
    filepath:   '$outputdir/projects/$P/$U/JuMonC_${J}.dat'
    columns:        'jobid,ts,nodeid,value0,value1,value2,value3,value4,value5,value6,value7,value8,value9'
    column_filemap: 'J:jobid'
    column_ts:      'ts'
    format:         'dat'
    format_str:      '%-10s %10d %12s "%s" "%s" "%s" "%s" "%s" "%s" "%s" "%s" "%s" "%s"'
    format_header:   '%-10s %10s %12s %8s %8s %8s %8s %8s %8s %8s %8s %8s %8s'
    column_filemap: 'J:jobid'
    data_database:   jumoncstate
    data_table:      jumonc_by_ts
    stat_database:   jobreport_stat_jumonc
    stat_table:      datasetstat_dat
    mngt_actions:   'compress_finished_files,archive_jobs_files'
