# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

- dataset:
    name: DBstat_csv
    set:        DBstat
    FORALL:     'T:VAR_DB_table'
    filepath:   '$outputdir/_internal/DBtab/DBtab_${{T}}.csv'
    columns:        'ts,nrows'
    # sqldebug:       'yes'     
    header:         'date,nrows'
    column_convert: 'ts->todate_1,nrows->null_if_empty'
    column_filemap: 'T:tabpath'
    format_str:      '%s,%d'
    column_ts:      'ts'
    format:         'csv'
    renew:          'daily(14:00)'
    data_database:   DBstat
    data_table:      LMLDBstat
    stat_database:   jobreport_stat_DBstat
    stat_table:      datasetstat

- dataset:
    name: DBstatALL_csv
    set:        DBstatALL
    filepath:   '$outputdir/_internal/DBtab/DBtab_ALL:ALLtab.csv'
    columns:        'ts,nrows'
    header:         'date,nrows'
    column_convert: 'ts->todate_1'
    format_str:      '%s,%d'
    column_ts:      'ts'
    format:         'csv'
    data_database:   DBstat
    data_table:      LMLDBstatALL
    stat_database:   jobreport_stat_DBstat
    stat_table:      datasetstat
    
- dataset:
    name: steptiming_csv
    set:        steptiming
    FORALL:     'I:VAR_WFstep'
    filepath:   '$outputdir/_internal/steptimings/step_${I}.csv'
    columns:        'startts,dt,cmplx'
    header:         'date,dt,cmplx'
    column_convert: 'startts->todate_1'
    column_filemap: 'I:id'
    format_str:      '%s,%.4f,%d'
    column_ts:      'startts'
    format:         'csv'
    time_aggr:      'span'
    renew:          'always'
    data_database:   steptimings
    data_table:      steptimings_time_aggr_ts
    stat_database:   jobreport_stat_steptimings
    stat_table:      datasetstat

- dataset:
    name: steptimeline_csv
    set:        steptimeline
    FORALL:     'I:VAR_WF'
    filepath:   '$outputdir/_internal/steptimings/steptimeline_${I}.csv'
    columns:        'startts,startts->ts_ms,dt->dt_ms,id,wf_name,nr,groupnr,cmplx'
    header:         'startdate,ts_ms,dt_ms,id,wf_name,nr,groupnr,cmplx'
    column_convert: 'startts->todate_fp,ts_ms->to_ms,dt_ms->to_ms'
    column_filemap: 'I:wf_name'
    format_str:      '%s,%.3f,%.6f,%s,%s,%d,%d,%d'
    column_ts:      'startts'
    format:         'csv'
    selecttimevar:   startts
    # sql_where:      '(startts>=wf_startts)'
    renew:          'always'
    data_database:   steptimings
    data_table:      steptimingscurrentstep
    stat_database:   jobreport_stat_steptimings
    stat_table:      datasetstat
    
    
- dataset:
    name: transfer_csv
    set:        transfer
    FORALL:     'N:VAR_transfer'
    filepath:   '$outputdir/_internal/steptimings/transfer_${N}.csv'
    columns:        'startts,dt,nfiles,nregfiles,ndirs,ncreate,ndelete,nregfilestrans,totalfilesize,totalfilesizetrans,totalbytessent,totalbytesrecv'
    header:         'date,dt,nfiles,nregfiles,ndirs,ncreate,ndelete,nregfilestrans,totalfilesize,totalfilesizetrans,totalbytessent,totalbytesrecv'
    column_convert: 'startts->todate_1,totalfilesize->toGiB,totalfilesizetrans->toMiB,totalbytessent->toMiB,totalbytesrecv->toMiB'
    column_filemap: 'N:ts_name'
    format_str:      '%s,%.4f,%d,%d,%d,%d,%d,%d,%.7f,%.4f,%.4f,%.4f'
    column_ts:      'startts'
    format:         'csv'
    renew:          'daily(14:00)'
    data_database:   transfer
    data_table:      transfer
    stat_database:   jobreport_stat_transfer
    stat_table:      datasetstat
    
