# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

data_database:   jobreport
data_table:      "joblist, jobmetrics, jobscores, pdffiles_reg, htmlfiles_reg"
data_table_join_col: jobid 
stat_database:   jobreport_json_stat
column_convert: 'firstts->hhmmss_sincenow,lastts->hhmmss_sincenow,ts->todate_std_hhmm,runtime->hhmm_short,
                 wall->hhmm_short, waittime->hhmm_short,
                 starttime->todate_std_hhmm,endtime->todate_std_hhmm,used_mem_max->MiBtoGiB,pckinout_avg->toMillion,
                 fs_home_Mbw_sum->MiBtoGiB, fs_home_Mbr_sum->MiBtoGiB,
                 fs_project_Mbw_sum->MiBtoGiB, fs_project_Mbr_sum->MiBtoGiB,
                 fs_scratch_Mbw_sum->MiBtoGiB, fs_scratch_Mbr_sum->MiBtoGiB,
                 fs_fastdata_Mbw_sum->MiBtoGiB, fs_fastdata_Mbr_sum->MiBtoGiB,
                 fs_all_Mbw_sum->MiBtoGiB, fs_all_Mbr_sum->MiBtoGiB,
                 gpu_memu_avg->toGiB,gpu_memu_max->toGiB,
                 gpu_pu_avg->toThousand,gpu_pu_max->toThousand,
                 nummsgs->onlygtnull,numerrnodes->onlygtnull, usage_avg->toPercent'
columns: 'jobid, ts, owner, wall, queue, account, mentor, runtime,
         starttime, endtime, numnodes, resid, waittime, nsteps,
         load_avg, usage_avg, ldscore, total_cores_avg, cpuscore,
         used_cores_avg, used_cores_phys_avg, used_cores_logic_avg, used_mem_max,
         nummsgs, numerrnodes, 
         fs_all_Mbw_sum, fs_all_Mbr_sum, fs_all_Moc_sum,
         fs_home_Mbw_sum, fs_home_Mbr_sum, fs_home_Moc_sum,
         fs_project_Mbw_sum, fs_project_Mbr_sum, fs_project_Moc_sum,
         fs_scratch_Mbw_sum, fs_scratch_Mbr_sum, fs_scratch_Moc_sum,
         fs_fastdata_Mbw_sum, fs_fastdata_Mbr_sum, fs_fastdata_Moc_sum,
         fs_all_w_score,fs_all_r_score,
         fs_home_w_score,fs_home_r_score,
         fs_project_w_score,fs_project_r_score,
         fs_scratch_w_score,fs_scratch_r_score,
         fs_fastdata_w_score,fs_fastdata_r_score,
         gpu_clkr_avg, gpu_clkr_max,
         gpu_memu_avg, gpu_memu_max, gpu_memur_avg,
         gpu_pu_avg, gpu_pu_max,
         gpu_sclk_avg, gpu_sclk_max, gpu_temp_avg, gpu_temp_max,
         gpu_usage_avg, gpu_usage_max, 
         gpu_pcie_tx_avg, gpu_pcie_tx_max,
         gpu_pcie_rx_avg, gpu_pcie_rx_max, 
         gpu_nvlink_tx_avg, gpu_nvlink_tx_max,
         gpu_nvlink_rx_avg, gpu_nvlink_rx_max, 
         gpu_dcgm_up_avg,gpu_dcgm_up_max,
         gpu_usage_score,total_score,
         firstts, lastts,
         mbinout_avg,pckinout_avg,
         ld_ndps, pdffile_reg, htmlfile_reg,
         rc_state,rc_state_color'
columns_not_used: 'jgroup, jstatus, detailedstatus, state, 
         wallsoft, queuedate, name, comment, totalcores, reason,
         totaltasks, totalgpus, dependency, qos, command, classprio,
         groupprio, userprio, sysprio, favored, restart, ArrayJobId, ArrayTaskId, 
         timetostart, posinqueue, ts_start, ts_end, stepspec, used_mem_min,
         istatus_avg, istatus_min, istatus_max, used_cores_min, used_cores_max, used_mem_avg,
         errmsgts, errmsgnodes, errmsgs,
         mbin_avg, mbin_min, mbin_max, mbout_avg, mbout_min,
         mbout_max, pckin_avg, pckin_min, pckin_max, pckout_avg, pckout_min,
         pckout_max,
         gpu_clk_avg, gpu_clk_min, gpu_clk_max, gpu_clkr_min, 
         gpu_link_avg, gpu_link_min, gpu_link_max, gpu_memf_avg, gpu_memf_min,
         gpu_memf_max, gpu_memt_avg, gpu_memt_min, gpu_memt_max, 
         gpu_memu_min, gpu_memur_min,
         gpu_memur_max, gpu_pciw_avg, gpu_pciw_min, gpu_pciw_max, gpu_pfst_avg,
         gpu_pfst_min, gpu_pfst_max, gpu_pu_min, 
         gpu_rtp_d_avg, gpu_rtp_d_min, gpu_rtp_d_max, gpu_rtp_s_avg,
         gpu_rtp_s_min, gpu_rtp_s_max, gpu_rtpd_avg, gpu_rtpd_min, gpu_rtpd_max,
         gpu_sclk_min, gpu_usage_min, gpu_temp_min, 
         gpu_pcie_tx_min, gpu_pcie_rx_min, 
         gpu_nvlink_tx_min, gpu_nvlink_rx_min, 
         gpu_node_up_avg,gpu_node_up_min,gpu_node_up_max,
         gpu_dcgm_up_min,
         firstts, lastts,
         fs_all_MbwR_avg, fs_all_MbwR_min, fs_all_MbwR_max, 
         fs_all_MbrR_avg, fs_all_MbrR_min, fs_all_MbrR_max, 
         fs_all_ocR_avg, fs_all_ocR_min, fs_all_ocR_max,
         falastts, fs_all_fslastts,fs_home_fslastts, fs_project_fslastts, fs_scratch_fslastts, 
         fs_fastdata_fslastts, gpulastts, gpu_eadm_d_sum,
         gpu_eadm_s_sum, gpu_eaom_d_sum, gpu_eaom_s_sum, gpu_evdm_d_sum,
         gpu_evdm_s_sum, gpu_evom_d_sum, gpu_evom_s_sum,'         
