###############################
# Project
###############################
- dataset:
    name: project_running_json
    set:                 json_project
    FORALL:             'P:VAR_project'
    filepath:           '$outputdir/projects/$P/running.json.gz'
    column_filemap:     'P:account'
    format:             'json'
    sql_where:          'owner!="unknown"'
    table_cache:        alljobs
    selecttimevar:      lastts
    selecttimerange:    TS_NOW-120,TS_NOW+1
    checksumvar:        lastts
    create_empty_files: yes
    data_database:      jobreport
    data_table:         joblist
    stat_database:      jobreport_json_stat
    stat_table:         datasetstat_project_running
    order:              "jobid DESC"
    %include "./jobreport_datafiles_json_common_joblist.yaml"

- dataset:
    name: project_today_json
    set:                 json_project
    FORALL:             'P:VAR_project'
    filepath:           '$outputdir/projects/$P/today.json.gz'
    column_filemap:     'P:account'
    format:             'json'
    sql_where:          'owner!="unknown"'
    table_cache:        alljobs
    selecttimevar:      lastts
    checksumvar:        lastts
    create_empty_files: yes
    selecttimerange:    TS_STARTOFTODAY,TS_NOW-120
    data_database:      jobreport
    data_table:         joblist
    stat_database:      jobreport_json_stat
    stat_table:         datasetstat_project_today
    order:              "jobid DESC"
    %include "./jobreport_datafiles_json_common_joblist.yaml"

- dataset:
    name: project_threeweeks_json
    set:                 json_project
    FORALL:             'P:VAR_project'
    filepath:           '$outputdir/projects/$P/threeweeks.json.gz'
    column_filemap:     'P:account'
    format:             'json'
    sql_where:          'owner!="unknown"'
    table_cache:        alljobs
    selecttimevar:      lastts
    selecttimerange:    TS_STARTOFTODAY-(21)*24*3600, TS_STARTOFTODAY
    checksumvar:        lastts
    create_empty_files: yes
    data_database:      jobreport
    data_table:         joblist
    stat_database:      jobreport_json_stat
    stat_table:         datasetstat_project_threeweeks
    order:              "jobid DESC"
    %include "./jobreport_datafiles_json_common_joblist.yaml"

- dataset:
    name: project_queueddetails_json
    set:        json_queued
    FORALL:             'P:VAR_project'
    filepath:           '$outputdir/projects/$P/queueddetails.json.gz'
    column_filemap:     'P:account'
    data_database:   jobreport
    data_table:      queuedjobs
    table_cache:     queuedjobs
    selecttimevar:   ts
    selecttimerange: TS_NOW-120,TS_NOW+1
    stat_table:      datasetstat_support
    stat_database:   jobreport_json_stat
    format:         'json'
    columns:        'userprio, jobid, ts, owner, account, mentor, queue, numnodes, state, qos, wall, restart, posinqueue, waittime, queuedate, timetostart, 
                     runtime, starttime, endtime, reason, dependency, chainid, wf_id, wf_jid, ArrayJobId, ArrayTaskId, resid, detailedstatus'
    column_convert: 'wall->hhmm_short,waittime->hhmmss_short,timetostart->hhmm_short,runtime->hhmm_short'
    order: "jobid DESC, userprio DESC"

- dataset:
    name: project_workflows_json
    set:        json_queued
    FORALL:     'P:VAR_project'
    filepath:   '$outputdir/projects/$P/workflows.json.gz'
    column_filemap: 'P:account'
    data_database:   jobreport
    data_table:      workflows,workflows_spec
    data_table_join_col: wf_id
    table_cache:     workflows
    stat_table:      datasetstat_support
    stat_database:   jobreport_json_stat
    format:         'json'
    order:          "wf_id DESC"
    %include "./jobreport_datafiles_workflow_columns.yaml"
